const products = [
    {
        id:1,
        image:"../image/dhapu-psb-2RV0Z0ft.png",
        catagoryies:"Soil Conditioner",
        name:"DHAPU-PSB",
        description:"Phosphate Solubilising Bio Fertilizer Phosphorus is another essential nutrient for plant growth. It plays a key..",
        rating:"4.9",
        stars: "⭐⭐⭐⭐☆",
       number:"(1288)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
    {
      id:2,
        image:"../image/d-king-C3N9a735.png",
        catagoryies:"Soil Conditioner",
        name:"D-KING",
        description:"Potash Mobilizing Bacteria Bio Fertilizer It is an excellent biofertilizer. It solubles insoluble potash in the soil and makes..",
        rating:"4.3",
        stars: "⭐⭐⭐⭐☆",
       number:"(535)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
    {
        id:3,
        image:"../image/dhapurhiza-sVZ0j5Pd.png",
               catagoryies:"Soil Conditioner",
        name:"DHAPURHIZA",
        description:"Mycorrhizal Bio-Fertilizer Dhapurhiza is an organic product based on VAM. It strengthens and..",
        rating:"4.7",
        stars: "⭐⭐⭐⭐☆",
       number:"(961)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
    {
        id:4,
        image:"../image/d-consortia-l-CVvrqBkZ.png",
        catagoryies:"Micronutrient Fertiliser",
        name:"D-CONSORTIA L",
        description:"Liquid Consortia It is a liquid organic product that stabilizes atmospheric nitrogen,..",
        rating:"4.5",
        stars: "⭐⭐⭐⭐☆",
       number:"(497)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"

    },
    {
        id:5,
        image:"../image/bio-potash-BByhnAXX.png",
                     catagoryies:"Soil Conditioner",
        name:"DHAPU GOLD GR",
        description:"Plant Biomass Based Organic Manure Dhapu Gold GR is useful for optimum growth and production of all crops,..",
        rating:"4.4",
        stars: "⭐⭐⭐⭐☆",
       number:"(839)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:6,
        image:"../image/dhapu-gold-gr-Cw509sXu.png",
                    catagoryies:"Soil Conditioner",
        name:"D-PROM",
        description:"Phosphate Rich Organic Manure Phosphate plays a vital role in providing balanced plant nutrition. PROM is ..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(1507)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:7,
        image:"../image/d-prom-BxFAKJot.png",
                    catagoryies:"Soil Conditioner",
        name:"DHAPU 19:19:19",
        description:"Potassium Nitrate N.P.K. 19:19:19 Dhapu is 19:19:19 crystalline powder which is completely soluble in water.It..",
        rating:"4.5",
        stars: "⭐⭐⭐⭐☆",
       number:"(1136)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:8,
        image:"../image/dhapu-19-19-19-DjZOMCjC.png",
                    catagoryies:"Micronutrient Fertiliser",
        name:"DHAPU 00:52:34",
        description:"Mono Potassium Phosphate N.P.K. 00:52:34 Dhapu 00:52:34 is crystalline powder which is completely soluble in water...",
        rating:"4.2",
        stars: "⭐⭐⭐⭐☆",
       number:"(547)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:9,
        image:"../image/dhapu-00-52-34-BwN8NHpW.png",
                   catagoryies:"Micronutrient Fertiliser",
        name:"DHAPU 13:00:45",
        description:"Potassium Nitrate N.P.K. 13:00:45 Dhapu is a 13:00:45 crystalline powder which is completely soluble in water. It..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:10,
        image:"../image/dhapu-13-00-45-axvfboHB.png",
                    catagoryies:"Micronutrient Fertiliser",
        name:"DHAPU 00:00:50",
        description:"Potassium Sulphate N.P.K. 00:00:50 Dhapu is a 00:00:50 crystalline powder which is completely soluble in water...",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:11,
        image:"../image/dhapu-0-0-54-D7Zd20Xk.png",
                    catagoryies:"Micronutrient Fertiliser",
        name:"D-IRON",
        description:"Chelated Iron as Fe-EDTA (12% Fe) D-Iron is a crystalline powder that is completely soluble in water.D-Iron..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:12,
        image:"../image/d-iron-D7BgRMm0.png",
                    catagoryies:"Soil Conditioner",
        name:"D-ZINC (12%)",
        description:"Chelated Zinc as Zn-EDTA (12%) Zinc is 100% 'chelated' with metal containing D-Zinc (12%). It is used to..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:13,
        image:"../image/d-zinc-12-euqyZ9xR.png",
                  catagoryies:"Micronutrient Fertiliser",
        name:"D-IRON (19%)",
        description:"Ferrous Sulphate-19% D-Iron (Ferrous Sulfate - 19%) drives photosynthesis in plants. It is an..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

        {
        id:14,
        image:"../image/d-iron-19-DWvEfMbJ.png",
                    catagoryies:"Micronutrient Fertiliser",
        name:"DHAPU POWER GR",
        description:"Calcium Nitrate Calcium nitrate (Calcium 18.8%, Nitrogen 15.5%) is a good nutrient for..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:15,
        image:"../image/dhapu-power-gr-DylqOfFE.png",
                    catagoryies:"Micronutrient Fertiliser",
        name:"D-90S",
        description:"Sulphur 90% D-90S contains sulfur in the form of 90% WG microgranules, which is..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:16,
        image:"../",
                     catagoryies:"Micronutrient Fertiliser",
        name:"DHAPU DHAN",
        description:"Potassium Humate 98% Technical Dhapudhan is a 100% water-soluble potassium humic acid in crystal/powder..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Micronutrient Fertiliser",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

        {
        id:17,
        image:"../image/dhapu-poshak-BEKUEhAy.png",
                  catagoryies:"Biostimulant/PGR",
        name:"DHAPU POSHAK",
        description:"Plant Growth & Immunity Booster Humic Acid, Amino Acid, Fulvic Acid, Seaweed Extract and/or other..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Biostimulant/PGR",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:18,
        image:"../image/d-booster-OMsWTZxN.png",
                  catagoryies:"Biostimulant/PGR",
        name:"D-BOOSTER",
        description:"Plant Growth Regulator D-Booster is an organic nutritional supplement intended for foliar..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Biostimulant/PGR",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:19,
        image:"../image/dhapu-green-DbyNEoGW.png",
                      catagoryies:"Biostimulant/PGR",
        name:"DHAPU GREEN",
        description:"Biostimulant Helps increase crop growth and disease resistance, as well as improved..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Biostimulant/PGR",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:20,
        image:"../image/dhapu-pride-ByUpkMmQ.jpeg",
                  catagoryies:"Insecticide",
        name:"DHAPUPRIDE",
        description:"Acetamipride 20% SP It is a ready-to-use water-soluble powder formulation of Acetamiprid..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:21,
        image:"../image/lava-king-BC1ZVXRG.jpg",
                  catagoryies:"Insecticide",
        name:"LAVAKING",
        description:"Chlorantraniliprole 18.5% SC It is an anthranilic diamide insecticide that targets a broad spectrum of pests,..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },


            {
        id:22,
        image:"../image/dhapu-para-o14Q8a--.jpg",
                  catagoryies:"Insecticide",
        name:"DHAPUPARA",
        description:"Paraquat Dichloride 24% SI It is a ready-to-use herbicide formulation delivering rapid contact..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
        {
        id:23,
        image:"../image/dhapu-star-D3yjAsgq.jpg",
                  catagoryies:"Insecticide",
        name:"DHAPUSTAR",
        description:"CTRP 9.3% + Lambda Cyhalothrin 4.6% ZC Dual-mode insecticide combining the systemic, longresidual action of..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:24,
        image:"../image/dkr-58-HCo52edF.jpg",
                  catagoryies:"Insecticide",
        name:"DKR - 58",
        description:"Phosphate Solubilising Bio Fertilizer Phosphorus is another essential nutrient for plant growth. It plays a key..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:25,
        image:"../image/d-phospower-P40QFbMB.jpg",
                  catagoryies:"Herbicide",
        name:"D- PHOSPOWER",
        description:"Chloropyriphos 20% EC A broad spectrum insecticide registered for the control of sucking..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Herbicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:26,
        image:"../image/dhapu-505-Dj4IIfWw.jpg",
                  catagoryies:"Insecticide",
        name:"DHAPU-505",
        description:"Chloropyriphos 50% + Cypermethrin 5% EC Dual-action emulsifiable concentrate combining a systemic..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:27,
        image:"../image/d-queen-1.9-DHWv-UoP.jpg",
                  catagoryies:"Insecticide",
        name:"D - Queen - 1.9",
        description:"Emamectin Benzoate 1.9% EC A semi-synthetic insecticide belonging to the avermectin group. It acts on the..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:28,
        image:"../image/dhapu-nashak-41-red-GX0hbw-W.jpeg",
                  catagoryies:"Insecticide",
        name:"DHAPUNASHAK - 41",
        description:"GLYPHOSATE 41% SL a broad-spectrum, non-selective systemic post-emergence herbicide..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:29,
        image:"../image/dhapu-hexa-BIEVmw4h.jpg",
                  catagoryies:"Insecticide",
        name:"DHAPUHEXA",
        description:"Hexaconazole 5% SC Highly effective systemic fungicide with protective, curative and..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:30,
        image:"../image/jayvir-top-CY5xrpFr.jpg",
                  catagoryies:"Herbicide",
        name:"JAYVIR - TOP",
        description:"GIBBERELLIC ACID 0.001% L naturally occurring plant growth hormone which regulates key..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Herbicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:31,
        image:"../image/d-oxy-D4Ifup0a.jpg",
                  catagoryies:"Fungicide",
        name:"D - OXY",
        description:"OXYFLUORFEN 23.5% EC A herbicide of diphyenyl-ether group used for selective weed control in a..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Fungicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:32,
        image:"../image/dhapu-sufai-BeRGoTzy",
                  catagoryies:"Fungicide",
        name:"DHAPUSAFAI",
        description:"MESOTRIONE 2.27% + ATRAZINE 22.7% SC Premix herbicide for maize and sugarcane that provides freedom from..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:33,
        image:"../image/d-feater-ChY9qPxD.jpg",
                  catagoryies:"Fungicide",
        name:"D - FEATER",
        description:"PROFENOPHOS 40% + CYPERMETHRIN 4% EC Dual protection by merging the contact action of Mancozeb with the systemic..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:34,
        image:"../image/dhapu-404-YMtgo-Fa.jpgpng",
                  catagoryies:"Biostimulant/PGR",
        name:"DHAPU - 404",
        description:"PROFENOPHOS 40% + CYPERMETHRIN 4% EC It is a highly effective insecticidal formulation combining the systemic..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Biostimulant/PGR",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:35,
        image:"../image/d-retila-CqFfdNx4.jpg",
                  catagoryies:"Herbicide",
        name:"D - RETILA",
        description:"PRETILACHLOR 50% EC It is a selective, post-emergence herbicide preferred for the control of..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Herbicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:36,
        image:"../image/d-tl-vT-ma5W0.jpg",
                  catagoryies:"Herbicide",
        name:"D - TL",
        description:"THIAMETHOXAM 12.6% + LAMBDA-CYHALOTHRIN 9.5% ZC It is a insecticidal formulation combining two synergistic active..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Herbicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:37,
        image:"../image/d-mida-CZy7HsvG.jpg",
                  catagoryies:"Herbicide",
        name:"D - MIDA",
        description:"IMIDACLOPRID 17.8% SL Systemic insecticide for controlling piercing-sucking pests across a wide..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Herbicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:38,
        image:"../image/d-maze-Bm3-2zVX.jpg",
                  catagoryies:"Insecticide",
        name:"D - MAZE",
        description:"IMAZETHYPYR 10% SL It is a selective, systemic herbicide belonging to the imidazolinone class. It..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:39,
        image:"../image/dkr-super-CA4K-gZq.jpg",
                  catagoryies:"Insecticide",
        name:"DKR - SUPER",
        description:"FIPRONIL 5% SC It is a broad-spectrum phenylpyrazole insecticide formulated as a suspensio..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:40,
        image:"../image/d-metman-XWdLTYhS.jpg",
                  catagoryies:"Insecticide",
        name:"D - METMAN",
        description:"Metalaxyl 8% + Mancozeb 64% WP Dual protection by merging the contact action of Mancozeb with the systemic..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:41,
        image:"../image/d-chipkoo-DL75uINb.jpeg",
                  catagoryies:"Insecticide",
        name:"D - KILLER",
        description:"Carbendazim 12% + Mancozeb 63% WP Carbendazim penetrates plant tissues, inhibiting fungal cell division, while..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

        {
        id:42,
        image:"../image/d-matrix-CJmFZHiG.jpg",
                  catagoryies:"Insecticide",
        name:"D - MATRIX",
        description:"METRIBUZINE 70% WP It is a selective, systemic, and contact triazinone herbicide effective both pre..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:43,
        image:"../image/hayan-koAJaGBd.jpg",
                  catagoryies:"Insecticide",
        name:"HAYAN",
        description:"Thiamethoxam 25% WG It is a broad-spectrum, systemic neonicotinoid insecticide formulated..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:44,
        image:"../image/d-chipkoo-DL75uINb.jpeg",
                  catagoryies:"Insecticide",
        name:"D - CHIPKOO",
        description:"Silicon based spreader Provides more uniform spray deposits on plants and improves coverage of..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:45,
        image:"../image/dhapu-delta-p-Bjm9NJqE.jpgpng",
                  catagoryies:"Adjuvants",
        name:"DHAPU - DELTA",
        description:"Deltamethrin 2.5% a high-quality synthetic pyrethroid insecticide designed for controlling a..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Adjuvants",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:46,
        image:"../image/dhapu-nashak-71-CNGuxvgQ.jpg",
                  catagoryies:"Soil Conditioner",
        name:"DHAPU-NASHAK-71",
        description:"Ammonium Salt of Glyphosate 71% SG It is non-selective, systemic, post-emergence herbicide in the form of..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:47,
        image:"../image/dhapu-tasla-CcJ8Cosq.jpg",
                  catagoryies:"Soil Conditioner",
        name:"DHAPU-TASLA",
        description:"Tebuconazole 10% + Sulphur 65% WG It is a combination fungicide that combines the systemic activity of..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:48,
        image:"../image/d-pendi-2-D8-jVt0m.jpg",
                  catagoryies:"Fungicide",
        name:"D - PENDI",
        description:"Pendimethalin 30% EC It is a pre-emergent selective herbicide supplied as an emulsifiable..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Fungicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:49,
        image:"../image/d-queen-5-bcI7FMB-.jpg",
                  catagoryies:"Herbicide",
        name:"D - Queen - 5",
        description:"Emamectin Benzoate 5% SG A potent avermectin insecticide used primarily for lepidopteran pest control..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Herbicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:50,
        image:"../image/dhapu-coc-CT8J8OF7.jpg",
                  catagoryies:"Insecticide",
        name:"DHAPU-COC",
        description:"COPPER OXYCHLORID 50% WP A copper-based broad-spectrum fungicide which controls fungal as well..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:51,
        image:"../image/dhaputap-gr-clSz0vSY.jpeg",
                  catagoryies:"Fungicide",
        name:"DHAPUTAP - GR",
        description:"Cartap Hydrochloride 4% GR Cartap Hydrochloride is a systemic insecticide for agricultural needs..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Soil Conditioner",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:52,
        image:"../image/rambaan-CE9j-pJ-.jpeg",
                  catagoryies:"Fungicide",
        name:"RAMBAAN",
        description:"RAMBAAN Quizalofop ethyl 7.5% + Imazethypyr 15% ec It is a broad-spectrum herbicide for post-emergence control of broad leaf &..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Fungicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },
            {
        id:53,
        image:"../image/karishma-aiulASAp.jpeg",
                  catagoryies:"Insecticide",
        name:"KARISHMA",
        description:"Pyriproxyfen 8% + Dinotefuran 5% + Diafenthiuron 18% SC This insecticide is absorbed quickly by every part of the crops through..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Insecticide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },

            {
        id:54,
        image:"../image/bio-potash-BByhnAXX.png",
                  catagoryies:"Fungicide",
        name:"D-PROM",
        description:"Phosphate Solubilising Bio Fertilizer Phosphorus is another essential nutrient for plant growth. It plays a key..",
        rating:"4.6",
        stars: "⭐⭐⭐⭐☆",
       number:"(452)",
    catagory:"Fungicide",
    subtitle:"Potash Mobilizing Bacteria Bio Fertilizer",
    dosageMain:"Soil: 10–20 kg per acre; Seed: 100–200 g per 2 L water; Spray: 200–500 ml per acre",
    variants:[
      "Granular: 4 kg",
      "Granular: 20 kg",
      "Liquid: 500 ml",
      "Liquid: 1000 ml",
    ],
    satisfaction:"86%",
    whatsapp:"919999999999"
    },



]